name: Deploy Release

on:
  workflow_run:
    workflows:
      - typecheck
    types:
      - completed

jobs:
  build_and_deploy:
    name: Build and Deploy Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/release' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node / cache yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        env:
          VITE_BACKEND_HOST: ${{ secrets.VITE_BACKEND_HOST }}
        run: |
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4
        with:
          BRANCH: gh-pages
          FOLDER: dist
