name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node / cache yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        env:
          VITE_BACKEND_HOST: ${{ secrets.DEV_VITE_BACKEND_HOST }}
        run: |
          yarn build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.DEV_AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.DEV_AWS_REGION }}
          SOURCE_DIR: dist
