name: Deploy Release

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy:
    name: Build and Deploy Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node / cache yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        env:
          VITE_BACKEND_HOST: ${{ secrets.VITE_BACKEND_HOST }}
        run: |
          yarn build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4
        with:
          BRANCH: gh-pages
          FOLDER: dist
